// Generated by CoffeeScript 1.3.3
(function() {
  var Package, async, build, fs;

  fs = require('fs');

  async = require('async');

  Package = require('../package');

  build = function(argv) {
    var pkg;
    pkg = null;
    return async.waterfall([
      function(cb) {
        return fs.readFile(argv.config, cb);
      }, function(file, cb) {
        var json, _i, _len, _ref;
        json = JSON.parse(file);
        pkg = new Package(json.name);
        _ref = json.files;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          file = _ref[_i];
          pkg.add({
            path: file,
            prefix: json.name
          });
        }
        return pkg.compile(cb);
      }, function(compiled, cb) {
        var output;
        output = argv.output || ("./" + pkg.name + ".js");
        console.info('writing to', output);
        return fs.writeFile(output, compiled, cb);
      }
    ], function(err) {
      if (err) {
        throw err;
      }
    });
  };

  build.options = {
    output: {
      alias: 'o'
    },
    config: {
      alias: 'c',
      "default": './package.json'
    }
  };

  module.exports = build;

}).call(this);
