// Generated by CoffeeScript 1.3.3
(function() {
  var async, build, fs, mallow;

  fs = require('fs');

  async = require('async');

  mallow = require('../index');

  build = function(argv) {
    var pkg;
    pkg = mallow(argv.config);
    return pkg.compile(function(err, output) {
      var file;
      if (err) {
        throw err;
      }
      file = argv.output || ("./" + pkg.name + ".js");
      console.info('writing to', file);
      return fs.writeFileSync(file, output);
    });
  };

  build.options = {
    output: {
      alias: 'o'
    },
    config: {
      alias: 'c',
      "default": './package.json'
    }
  };

  module.exports = build;

}).call(this);
