// Generated by CoffeeScript 1.3.3
(function() {
  var Package, fs, http, server;

  fs = require('fs');

  http = require('http');

  Package = require('../package');

  server = function(argv) {
    return fs.readFile(argv.config, function(err, file) {
      var json, pkg, _i, _len, _ref;
      if (err) {
        throw err;
      }
      json = JSON.parse(file);
      pkg = new Package(json.name);
      _ref = json.files;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        pkg.add({
          path: file,
          prefix: json.name
        });
      }
      return http.createServer(pkg.server).listen(argv.port);
    });
  };

  server.options = {
    port: {
      alias: 'p',
      "default": 8642
    },
    config: {
      alias: 'c',
      "default": './package.json'
    }
  };

  module.exports = server;

}).call(this);
