// Generated by CoffeeScript 1.3.3
(function() {
  var fs, http, mallow, server;

  fs = require('fs');

  http = require('http');

  mallow = require('../index');

  server = function(argv) {
    var pkg;
    pkg = mallow(argv.config);
    http.createServer(pkg.server).listen(argv.port);
    return console.log("listening on 0.0.0.0:" + argv.port);
  };

  server.options = {
    port: {
      alias: 'p',
      "default": 8642
    },
    config: {
      alias: 'c',
      "default": './package.json'
    }
  };

  module.exports = server;

}).call(this);
