// Generated by CoffeeScript 1.4.0
(function() {
  var Bundle;

  Bundle = require('./bundle');

  exports["new"] = function(dir) {
    var bundle;
    bundle = new Bundle;
    bundle.add(dir);
    return bundle;
  };

  exports.errorHandler = function(err, req, res, next) {
    if (res.getHeader('Content-Type') === 'application/javascript') {
      return res.send(500, "console.error(" + (JSON.stringify(err.toString())) + ");");
    } else {
      return next(err);
    }
  };

}).call(this);
