// Generated by CoffeeScript 1.4.0
(function() {
  var Module, Package, Queue, async,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  async = require('async');

  Package = require('./package');

  Module = require('./module');

  exports["new"] = function() {
    return new Queue;
  };

  Queue = (function() {

    function Queue() {
      this.invoke = __bind(this.invoke, this);

      var _this = this;
      this.queue = async.queue(this.invoke, 5);
      this.modules = [];
      this.queue.drain = function() {
        return typeof _this.done === "function" ? _this.done() : void 0;
      };
    }

    Queue.prototype.invoke = function(task, cb) {
      var _this = this;
      console.log("" + task.name);
      return task.fn.call(this, function(err) {
        if (err) {
          return _this.stop(err);
        } else {
          return cb();
        }
      });
    };

    Queue.prototype.add = function(name, fn) {
      return this.queue.push({
        name: name,
        fn: fn
      });
    };

    Queue.prototype.stop = function(err) {
      this.queue.concurrency = 0;
      return typeof this.done === "function" ? this.done(err) : void 0;
    };

    Queue.prototype.compilePackage = function(dir) {
      var pkg;
      pkg = Package["new"](dir);
      return this.add("compile package " + pkg.name, function(cb) {
        return pkg.compile(this, cb);
      });
    };

    Queue.prototype.compileModule = function(file, pkg) {
      var module;
      module = Module["new"](file, pkg);
      this.modules.push(module);
      return this.add("compile module " + module.name, function(cb) {
        return module.compile(cb);
      });
    };

    return Queue;

  })();

}).call(this);
